### ISSUE TITLE
请教一下您的这个Demo项目头部的分类与标签问题

### ISSUE THREAD

**Issue by shilazi** [iTimeTraveler/iTimeTraveler.github.io#1]
大神开发者，你好！本人刚折腾Hexo静态博客，采主题东南下，悠然见您做的主题，很想仿照您的demo项目做博客，博客的架子已经搭起来了，现在遇到3个解决不掉的问题：
1、博客头部的**分类**与**标签**无法做到与您的一样，请问您是如何实现的
2、头部点入的分类与标签的内容，捐献按钮是如何隐藏的
3、关于菜单，您做的太过于张扬，大图如何隐藏
我刚入Hexo(Node.js)这个门，很多可能是你们看起来的常识，作为入门的我们都不知道，还望细心指点一下。先行谢过您嘞！

**Comment by shilazi** [comment]
issun:isiren issun$ vim _config.yml 

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 开到荼蘼
subtitle: 听说~
description: 念去去，千里烟波
author: Mr.Ssun
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false

```
---

以上是默认配置，以下是主题配置

---

```yml
# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Header Menu
menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  About: /about
rss: /atom.xml

since: 2017

# Set default keywords (Use a comma to separate)
keywords: ""

# Put your favicon.ico or avatar.jpg into `hexo-site/themes/hiker/source/` directory.
avatar: 
  enable: true
  border: true
  width: 124
  height: 124
  top: 0
  url: css/images/mylogo.jpg


# Homepage
# eg. home_background_image: [css/images/home-bg.jpg, http://t.cn/RMbvEza]
# eg. mode: image | polyline | trianglify
home_background_image:
  enable: true
  mode: image
  rolling: true
  url: [css/images/home-bg.jpg, css/images/sample.jpg, https://source.unsplash.com/collection/954550/1920x1080]

home_logo_image:
  enable: false
  border: false
  url: css/images/homelogo.jpg


# AboutPage background
about_big_image: [css/images/pose.jpg, css/images/sample.jpg, https://source.unsplash.com/collection/954550/1920x1080]


# Archive pagination
archive_pagination: true


# Post Article's Content
post_catalog:
  enable: true


# Content
fancybox: true


# Sidebar
sidebar: right
widgets:
- social
- category
- tag
- tagcloud
- archive
- recent_posts


# Social Links
# Key is the name of FontAwsome icon.
# Value is the target link (E.g. GitHub: https://github.com/iTimeTraveler)
social:
  Github: https://github.com/iTimeTraveler
  #Weibo: http://www.yoursite.com
  #Twitter: 
  #Facebook: 
  #Google-plus: 
  #Instagram: 
  #Pinterest: 
  #Flickr: 
  #email:


# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false


# comment ShortName, you can choose only ONE to display.
gentie_productKey: #your-gentie-product-key
duoshuo_shortname: 
disqus_shortname: 
livere_shortname: MTAyMC8zMDkwNy86NDU1
uyan_uid: 
wumii: 


# Code Highlight theme
# Available value:
#    default | gray | normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: normal


# Article theme color
# Available value:
#    random | orange | blue | red | green | black
theme_color: random


# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive


# widget behavior
archive_type: 'monthly'
show_count: true

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification:
baidu_site_verification:
qihu_site_verification:

# Miscellaneous
google_analytics:
gauges_analytics:
baidu_analytics:
tencent_analytics:
twitter:
google_plus:
fb_admins:
fb_app_id:

# Facebook SDK Support.
# https://github.com/iissnan/hexo-theme-next/pull/410
facebook_sdk:
  enable: false
  app_id:       #<app_id>
  fb_admin:     #<user_id>
  like_button:  #true
  webmaster:    #true

# CNZZ count
cnzz_siteid: 1260716016

# busuanzi count
# http://busuanzi.ibruce.info/
show_busuanzi_view_counts: true


# donation button
donate:
    enable: true
    message: '如果觉得我的文章对您有用，请随意打赏。您的支持将鼓励我继续创作!'
    wechatImage: https://raw.githubusercontent.com/iTimeTraveler/iTimeTraveler.github.io/site/source/about/donate/images/WeChanQR.png
    alipayImage: https://raw.githubusercontent.com/iTimeTraveler/iTimeTraveler.github.io/site/source/about/donate/images/AliPayQR.jpg

```

**Comment by iTimeTraveler** [comment]
@isiren 我看了下你的配置，可能是最外层的Hexo根目录下的`_config.yml`文件配置不对，看上去是落掉了一部分。下面是我的这个配置。你试着换了看看可以不

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: iTimeTraveler
subtitle:
description: Someone knock at the door.
author: Mr.Seven
language: zh-CN
timezone: 

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://github.com/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
  - README.md
  - README.cn.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: true
future: true
mathjax: false
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hiker

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: 
  type: git
  repository: git@github.com:iTimeTraveler/iTimeTraveler.github.io.git
  branch: master

```

**Comment by shilazi** [comment]
@iTimeTraveler 大神，默认配置是由于使用Mac的Shell复制的，没有贴完整，以下为剩余的部分。我仔细看了一下。除了post_asset_folder: true; relative_link: true; future: true，其他都一样。还望您能看一下我在第一个issue问的三个问题。
```
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: maupassant
# theme: material
# theme: cyanstyle
theme: hiker

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:isiren/isiren.github.com.git
  branch: master
```
